---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: db
  namespace: flux-system
spec:
  chart:
    spec:
      chart: postgres
      sourceRef:
        kind: HelmRepository
        name: lfs269
  install: {}
  interval: 1m0s
  targetNamespace: instavote
  values:
    serivce:
      name: db
    settings:
      authMethod: trust

