---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: instavote
  namespace: instavote
spec:
  secretRef:
    name: github-token
  url: https://github.com/lexarflash8g/instavote-deploy.git

---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: github-instavote
  namespace: instavote
spec:
  address: https://github.com/lexarflash8g/instavote-deploy
  secretRef:
    name: github-token


