apiVersion: v1
data:
  password: Z2hwX2laODRpY2dtVk1uUGJ1aFNldGJQSjJhbU54bXlYNTBGbW9oRw==
  username: bGV4YXJmbGFzaDhn
kind: Secret
metadata:
  creationTimestamp: "2021-08-09T23:35:33Z"
  name: github-instavote
  namespace: flux-system
  resourceVersion: "4916295"
  uid: e1e9b4b2-4d5a-4222-820f-9c9d72c73777
type: Opaque
